// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUq339UjZMKy-6Byk3yY5gHqV1bRvR-6Q',
    appId: '1:675110619140:web:f28b155c84514014fa4d51',
    messagingSenderId: '675110619140',
    projectId: 'shuumy-1a9cc',
    authDomain: 'shuumy-1a9cc.firebaseapp.com',
    storageBucket: 'shuumy-1a9cc.appspot.com',
    measurementId: 'G-RNRF94PNH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyAgfhMSsviKvsQ1btr4tyNJIZK2gZuVo',
    appId: '1:675110619140:android:024b77607a8d1b8bfa4d51',
    messagingSenderId: '675110619140',
    projectId: 'shuumy-1a9cc',
    storageBucket: 'shuumy-1a9cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDy-EYACujjHzTXnPQIK3EK1_o1xbum6Q',
    appId: '1:675110619140:ios:779cc1c33724846ffa4d51',
    messagingSenderId: '675110619140',
    projectId: 'shuumy-1a9cc',
    storageBucket: 'shuumy-1a9cc.appspot.com',
    iosClientId: '675110619140-nqdepgfu5k38ahrjna59afp5iu3cr044.apps.googleusercontent.com',
    iosBundleId: 'com.example.shuumy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDy-EYACujjHzTXnPQIK3EK1_o1xbum6Q',
    appId: '1:675110619140:ios:779cc1c33724846ffa4d51',
    messagingSenderId: '675110619140',
    projectId: 'shuumy-1a9cc',
    storageBucket: 'shuumy-1a9cc.appspot.com',
    iosClientId: '675110619140-nqdepgfu5k38ahrjna59afp5iu3cr044.apps.googleusercontent.com',
    iosBundleId: 'com.example.shuumy',
  );
}
